"""Deployment-only integrity checks; no scientific outputs are generated."""

from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from data.v1_loader import (  # noqa: E402
    BIOLOGICAL_CONTEXTS,
    CONFIDENCE_LABELS,
    CURATED_CANDIDATE_STRUCTURES,
    PUBLISHED_FEATURES,
    UNRESOLVED_RECORDS,
)
from services.feature_queries import feature_catalog  # noqa: E402
from services import frozen_docking as fd  # noqa: E402


ACTIVE_CODE = [
    ROOT / "app.py",
    *sorted((ROOT / "modules").glob("*.py")),
    *sorted((ROOT / "services").glob("*.py")),
]


def test_v1_evidence_contract() -> None:
    catalog = feature_catalog()
    assert len(PUBLISHED_FEATURES) == 81
    assert len(BIOLOGICAL_CONTEXTS) == 15
    assert int(catalog["has_interpretation"].sum()) == 70
    assert len(CURATED_CANDIDATE_STRUCTURES) == 55
    assert PUBLISHED_FEATURES["confidence_symbol"].value_counts().to_dict() == {"?": 32, "??": 27, "*": 11, "UK": 11}
    assert PUBLISHED_FEATURES["identification_confidence"].notna().all()
    assert set(PUBLISHED_FEATURES["identification_confidence"]) == set(CONFIDENCE_LABELS.values())
    assert len(UNRESOLVED_RECORDS) > 0


def test_docking_contract() -> None:
    result = fd.scientific_contract()
    assert result["ok"], [name for name, passed in result["checks"].items() if not passed]


def test_runtime_assets_and_relative_paths() -> None:
    for path in fd.SOURCES.values():
        assert path.is_file(), path
        assert ROOT in path.parents
    for row in fd.representative_complexes().itertuples():
        assert (ROOT / row.representative_pose_path).is_file()
    for pdb_id in ("4Z39", "4Z45"):
        assert fd.prepared_receptor_path(pdb_id).is_file()
    assert all(fd.source_bytes(key) for key in fd.DISPLAY_DOWNLOADS.values())


def test_missing_docking_asset_fails_explicitly() -> None:
    original = fd.SOURCES["pairs"]
    fd.SOURCES["pairs"] = ROOT / "data" / "docking" / "intentionally_missing.csv"
    try:
        try:
            fd._read_csv("pairs")
        except FileNotFoundError as exc:
            assert "Frozen docking source is unavailable" in str(exc)
        else:
            raise AssertionError("Missing frozen docking data did not raise FileNotFoundError")
    finally:
        fd.SOURCES["pairs"] = original


def test_legacy_demo_is_not_active() -> None:
    removed = (
        "data/sample_data.py",
        "modules/bioassay.py",
        "modules/receptor_docking.py",
        "modules/agent_team_.py",
    )
    assert all(not (ROOT / path).exists() for path in removed)
    app = (ROOT / "app.py").read_text(encoding="utf-8")
    assert "sample_data" not in app
    assert "v1_docking_explorer" in app


def test_no_private_windows_runtime_paths() -> None:
    drive_path = re.compile(r"(?<![A-Za-z])[A-Za-z]:[\\/](?![\\/])")
    offenders = []
    for path in ACTIVE_CODE:
        if drive_path.search(path.read_text(encoding="utf-8")):
            offenders.append(path.relative_to(ROOT).as_posix())
    assert not offenders, offenders


def test_public_runtime_has_no_internal_phase_paths_or_openai() -> None:
    forbidden = (
        "phase5d1_outputs",
        "phase5d2_outputs",
        "phase5d3_outputs",
        "phase5d3a_outputs",
        "phase5d3b_outputs",
        "from openai",
        "import openai",
        "OPENAI_API_KEY",
    )
    offenders = []
    for path in ACTIVE_CODE:
        text = path.read_text(encoding="utf-8")
        if any(value in text for value in forbidden):
            offenders.append(path.relative_to(ROOT).as_posix())
    assert not offenders, offenders


def test_confidence_is_descriptive_in_active_interface() -> None:
    feature_page = (ROOT / "modules" / "phase5c3_feature_library.py").read_text(encoding="utf-8")
    evidence_page = (ROOT / "modules" / "phase5c3_evidence.py").read_text(encoding="utf-8")
    assistant = (ROOT / "services" / "research_assistant.py").read_text(encoding="utf-8")
    assert "format_func=lambda value: CONFIDENCE_LABELS[value]" in feature_page
    assert "CONFIDENCE_EXPLANATION" in feature_page and "CONFIDENCE_EXPLANATION" in evidence_page
    assert "Identification confidence:" in evidence_page
    assert "Original published notation:" in evidence_page
    assert "not generated by VOC·BIO" in assistant


if __name__ == "__main__":
    tests = [value for name, value in sorted(globals().items()) if name.startswith("test_") and callable(value)]
    for test in tests:
        test()
        print(f"PASS {test.__name__}")
    print(f"PASS {len(tests)} deployment integrity tests")
