"""Phase 5D.4 scientific data and Streamlit integration tests."""

from pathlib import Path
import sys

import numpy as np
import pandas as pd
from streamlit.testing.v1 import AppTest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from services import frozen_docking as fd
from data.v1_loader import CONFIDENCE_LABELS, PUBLISHED_FEATURES
from services.feature_queries import feature_catalog
from services.research_assistant import answer_question


def test_frozen_scientific_contract():
    result = fd.scientific_contract()
    assert result["ok"], [name for name, ok in result["checks"].items() if not ok]


def test_published_confidence_codes_preserved_with_descriptive_derivatives():
    source = pd.read_csv(ROOT / "data/v1/v1_published_features.csv", dtype=str, keep_default_na=False)
    assert "published_confidence_notation" not in source.columns
    assert "identification_confidence" not in source.columns
    expected = {"*": 11, "?": 32, "??": 27, "UK": 11}
    assert source["confidence_symbol"].value_counts().to_dict() == expected
    assert PUBLISHED_FEATURES["confidence_symbol"].value_counts().to_dict() == expected
    assert PUBLISHED_FEATURES["published_confidence_notation"].equals(PUBLISHED_FEATURES["confidence_symbol"])
    assert PUBLISHED_FEATURES["identification_confidence"].notna().all()
    assert set(PUBLISHED_FEATURES["identification_confidence"]) == set(CONFIDENCE_LABELS.values())
    exported = feature_catalog().to_csv(index=False)
    assert "published_confidence_notation" in exported.splitlines()[0]
    assert "identification_confidence" in exported.splitlines()[0]


def test_assistant_uses_descriptive_confidence_terminology():
    answer = answer_question("What do the identification-confidence categories mean?")
    assert "11 Authentic-standard supported" in answer.answer
    assert "32 Tentative identification, higher library match" in answer.answer
    assert "27 Tentative identification, lower library match" in answer.answer
    assert "11 Unknown features" in answer.answer
    assert "not generated by VOC·BIO" in answer.answer
    assert "confirmed chemical identities" in answer.caution
    assert {"published_confidence_notation", "identification_confidence"}.issubset(answer.records.columns)


def test_exact_headline_values_and_correlation():
    pairs = fd.pair_results()
    grouped = pairs.groupby("receptor_name")["median_rank1_score"]
    assert np.isclose(grouped.median()["MvicOBP3"], -4.712, atol=1e-12)
    assert np.isclose(grouped.median()["NribOBP3"], -4.7895, atol=1e-12)
    comparison = fd.table("comparison")
    assert np.isclose(comparison[["MvicOBP3", "NribOBP3"]].corr().iloc[0, 1], 0.9600100221, atol=1e-10)
    bio39 = comparison.set_index("bio_id").loc["Bio39"]
    assert np.isclose(bio39["Mvic_minus_Nrib_kcal_mol"], 0.525, atol=1e-12)


def test_corrected_interactions_and_dummy_filter():
    interactions = fd.table("interactions")
    bio39 = interactions.query("PDB_ID == '4Z45' and bio_id == 'Bio39'")
    distances = {(row.receptor_atom, row.ligand_atom): row.minimum_strict_heavy_atom_distance_A for row in bio39.itertuples()}
    assert np.isclose(distances[("N", "O")], 2.905, atol=1e-12)
    assert np.isclose(distances[("CB", "O")], 3.591, atol=1e-12)
    representative = fd.representative_complexes().query("bio_id == 'Bio38'").iloc[0]
    text = fd.filtered_pose_text(representative["representative_pose_path"], "Bio38")
    atom_names = [line[12:16].strip() for line in text.splitlines() if line.startswith(("ATOM", "HETATM"))]
    assert "G0" not in atom_names


def test_stereochemistry_and_post_hoc_wording_present():
    module_text = (ROOT / "modules/v1_docking_explorer.py").read_text(encoding="utf-8")
    assert all(bio in module_text for bio in ["Bio17", "Bio4", "Bio21"])
    assert "st.info(fd.STEREO_CAVEAT)" in module_text
    assert "source annotation does not establish stereochemistry" in fd.STEREO_CAVEAT
    assert "post hoc descriptive" in module_text.lower()
    assert "not a prospectively frozen Phase 5D.2 validation criterion" in module_text


def test_validation_statistics():
    values = fd.validation_results().set_index("PDB_ID")
    assert values.loc["1DQE", "rank1_success_fraction"] == "0/5"
    assert values.loc["1DQE", "best_of_10_success_fraction"] == "1/5"
    assert np.isclose(values.loc["1DQE", "minimum_RMSD"], 1.7936)
    assert values.loc["2WC6", "rank1_success_fraction"] == "1/5"
    assert values.loc["2WC6", "best_of_10_success_fraction"] == "5/5"
    assert np.isclose(values.loc["2WC6", "median_best_of_10_RMSD"], 1.3438)
    assert values.loc["3N7H", "rank1_success_fraction"] == "5/5"
    assert values.loc["3N7H", "best_of_10_success_fraction"] == "5/5"
    assert np.isclose(values.loc["3N7H", "median_rank1_RMSD"], 0.6453)


def test_no_legacy_production_route_or_score_conversion():
    app_text = (ROOT / "app.py").read_text(encoding="utf-8")
    module_text = (ROOT / "modules/v1_docking_explorer.py").read_text(encoding="utf-8")
    assert "from modules.v1_docking_explorer" in app_text
    assert "from modules.v1_docking_notice" not in app_text
    assert "RferOBP4" not in module_text
    assert "estimated_ki" not in module_text.lower()
    assert "no biological p-values are calculated" in module_text.lower()


def _open_app(page: str):
    app = AppTest.from_file(str(ROOT / "app.py"), default_timeout=90)
    app.run()
    app.radio[0].set_value(page).run()
    assert not app.exception, [str(item.value) for item in app.exception]
    return app


def test_all_existing_top_level_routes():
    routes = [
        "Dashboard", "Published GC-MS Features", "Chemical Structure Explorer",
        "Biological & Sample Contexts", "Published Feature Statistics", "Evidence Explorer",
        "Docking Predictions", "Feature-Context Network", "Structural Similarity Explorer",
        "References / Data Sources", "Research Team Assistant",
    ]
    for route in routes:
        _open_app(route)


def test_all_docking_subviews():
    app = _open_app("Docking Predictions")
    for view in [
        "Overview", "Receptor × VOC matrix", "VOC explorer", "Receptor comparison",
        "Seed variability", "Pose explorer", "Docking validation", "Methods & provenance",
    ]:
        app.selectbox[0].set_value(view).run()
        assert not app.exception, (view, [str(item.value) for item in app.exception])


if __name__ == "__main__":
    tests = [value for name, value in sorted(globals().items()) if name.startswith("test_") and callable(value)]
    for test in tests:
        test()
        print(f"PASS {test.__name__}")
    print(f"PASS {len(tests)} Phase 5D.4 tests")
